server:
  port: 8800
spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    url: jdbc:mysql://1.92.109.205:3306/InfinityLogDB?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai&tinyInt1isBit=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: binfinity
    password: Cb050328_password
  redis:
    host: 1.92.109.205
    port: 6379
    database: 8
    timeout: 3000
    password: Anchor_Mar25

# application.yml 或 application.properties 中加上：
mybatis-plus.configuration.log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#==============================knife4j配置==============================
knife4j:
  enable: true
  basic:
    enable: true
    username: Binfinity
    password: Cb050328
  openapi:
    title: Infinity.log博客接口文档
    description: By Binfinity
    # aaa"
    email: binfinity@qq.com
    concat: Binfinity
    url: http://localhost:1234/
    version: v1.3
    group:
      test1:
        group-name: 分组名称
        api-rule: package
        api-rule-resources:
          - com.mojian

#==============================公众号配置==============================
wechat:
  app-id:
  # 公众号AppSecret
  secret:
  # 公众号Token
  token:
  # 公众号AES Key
  aesKey:

  appletAppId:
  appletSecret:

#==============================豆包推理AI配置=======================================
ai:
  # API Key
  apiKey: 1098519a-93ef-418e-a547-a54fa30d3626
  baseUrl: https://ark.cn-beijing.volces.com/api/v3
  # 推理接入点ID
  model:

#==============================邮箱配置=======================================
mail:
  smtp:
    host: smtp.yeah.net
    port: 25
    email: binfinity2024@yeah.net
    password: YBwmS3AREq766EsA

#============================第三方登录配置信息===================================
qq:
  app-id: 101995894
  app-secret: 238689485c7d930b7da82545505471aa
  redirect-url: http://1.92.109.205:8800/api/auth/callback/qq
weibo:
  app-id:
  app-secret:
  redirect-url: https://localhost:8800/mojian/api/auth/weibo

gitee:
  app-id: af286a061d6808341dd1e99cde152ada02d1e064aac04d2a8b3d5e744f42e9a7
  app-secret: 62dd0cce76f7c6416faf0594562012312cb9e75c9a5392feaa9b16fd30c18389
  redirect-url: http://1.92.109.205:8800/api/auth/callback/gitee


github:
  app-id: Ov23likAMEdljwAf8LMs
  app-secret: 712c7018c17d725eca478d07b8ad25457aca5566
  redirect-url: http://1.92.109.205:8800/api/auth/callback/github




